### PR TITLE
WRI-UNFCCC update notebook wri-unfccc-mapping-json

### LINKED ISSUE #106: WRI UNFCCC - Mapping - Update ghgg data mapping
@lara-krm 
Hello,
You can make pull request of updated notebook and ammped data and link it to this issue

Changes include:
- transform "provider" field into "scenario"
- remove information from datasrouce description since it generates big mapped json file. Data source properties will be deduced from data catalog

### PR DESCRIPTION
**Pull request by lara-krm**

### CODE REVIEW

**Comment by bouffan** [comment]
@CJeannesson Small question: is it normal that the mapped data have only 2 countries ? Is it because the entire mapped file is too big for github ?

**Review by bouffan — CHANGES_REQUESTED** [review]
Hi ! 

So I only have two comments before merging 

- @lara-krm in the mapped data of UNFCCC, there is a null entry in the field description of the dictionary properties that can be left out of the mapped data
- @CJeannesson As I commented in the thread, there are only 2 countries in the mapped data for now 

Otherwise, everything seems great !

**Comment by CJeannesson** [comment]
Hi!
Yes, only two countries have been uploaded on github for testing purposes, as the entire file is too big. The complete mapped data can be found on S3 though.

**Comment by bouffan** [comment]
@CJeannesson Ok thanks for the answer !

**Pull request merged**
