### PR TITLE
Wri - UNFCCC 

### LINKED ISSUE #50: WRI-CAIT - Test mapping with OGS data model

### LINKED ISSUE #69: UNFCCC- Mapping with OGS integration data model
Mapping rules: https://docs.google.com/spreadsheets/d/1CnTpHjZZZepgJ1o1VuQUN61ZaLLRtM1OhZzJU9HCPaY/edit#gid=0

### PR DESCRIPTION
**Pull request by lara-krm**
@S-AI-F 

This pull request concerns : 
- updating the notebook EDA WRI-UNFCCC
- adding the 3 datasets I use 
- creating the notebook mapping WRI-UNFCC
- the json file in the mapped directory

### CODE REVIEW

**Comment by S-AI-F** [comment]
Thank you @lara-krm 

@bouffan wil check if the data has been mapped correctly. Once the json file is validated, we can move to the next step by changing the input/output file to get and store data from aws s3.

**Review by bouffan — CHANGES_REQUESTED** [review]
Hi everyone ! 

I have just finished looking at the notebook + mapped data. It is great ! I only have a few minor comments before merging. 

First, the name of the gas needs to be modified. In the current version, the name of the gas is the original name from the dataset, while it should be one of the possibilities of ogs (so "Aggregate GHGs" should be "kyotogases").
Also, in the notebook, be careful because the mapped dictionary used for the gases is actually the mapped dictionary for the sector.

The second comment I have is that, if I am not mistaken, all null entries of optional entries should be ignored. So in your case, you don't have to print "name" in geo_component and "data_source_code" (right @S-AI-F ?)

Finally, @S-AI-F there is a long entry for the decription of the dataset that is "properties:description" : 
"The World Resources Institute is a global research non-profit organization. Regarding GHG emissions, WRI provides data from several sources including UNFCCC, the United Nations Framework Convention on Climate Change. The UNFCCC data is splitted in 2 parties, the Annex I Parties and the nonAnnex I Parties."
The dataset is not too big, so I think it is ok to repeat it at each line, but I wanted to ask you your opinion ?

**Comment by CJeannesson** [comment]
The CAIT mapped data (two countries) has been pushed. Accordingly, a null entry for optional entries has been sometimes added. is there a final decision about it ?

**Comment by bouffan** [comment]
@CJeannesson I think that null entries should be omitted for optional entries (at least, all the other mapped notebooks have done this for now !)

**Review by bouffan — CHANGES_REQUESTED** [review]
Hi ! 

I have only small modifications to suggest before merging.
- the mapped gas name are not exactly the same than in the model. As it might be case sensivtive, it should be CO2 not co2, and same for all the specific gases
- the null entries should be omitted

**Comment by CJeannesson** [comment]
Hi !

The requested corrections for the CAIT mapped data have been done.

**Review by bouffan — APPROVED** [review]
I just looked at the corrections of the CAIT data and everything looks good to me !

**Comment by bouffan** [comment]
So i approved the changes for the CAIT data, but to my understanding there are still some changes to do on the WRI-UNFCCC data!

**Pull request merged**
