### PR TITLE
oecd mapping

### LINKED ISSUE #67: OECD - Mapping with OGS integration data model
Mapping rules: https://docs.google.com/spreadsheets/d/1CnTpHjZZZepgJ1o1VuQUN61ZaLLRtM1OhZzJU9HCPaY/edit#gid=0

### PR DESCRIPTION
**Pull request by egregorimar**
#67

### CODE REVIEW

**Comment by S-AI-F** [comment]
@bouffan Do you think you can review this mapping pull request?
Thanks :)

**Comment by bouffan** [comment]
@S-AI-F Sure ! I will do it asap (today or in the weekend)

**Review by bouffan — CHANGES_REQUESTED** [review]
@egregorimar I just finished looking at the mapping related things in the commits!

I have just some comments regarding a couple of points:

- I think that there is a problem with the mapped sectors. In the notebook, you have two sectors that have a strange mapping:

     mapped_sectors["1A3 - Transport"]="total_excluding_LUCF"
     mapped_sectors["1C - CO2 from Transport and Storage"]="transportation"

 this mapping does not correspond to the ones you have put in the Excel summary of the mapping, and should be "transportation" and "transport_storage" respectively

- There is an entry "data_source_code" in the field "properties" for the geo-component, that is not existent in the current model. In addition, the value inside the field is the same than the one in the "identifier" field of "id"

- @S-AI-F there is a long description in the field "description for the data_source:

"The OECD (Organisation for Economic Co-operation and Development) is an intergovernmental economic organisation with 37 member countries, founded in 1961 to stimulate economic progress and world trade. OECD takes environmental data from UNFCCC's National Inventory Submissions."

Is it OK or is it an information that can be placed outside of the mapping data ?

**Comment by S-AI-F** [comment]
@bouffan @egregorimar 

- concerning data_source_code, I have already discussed with Ernesto and we decided to add this field in his datasource because he has a kind of "external identifier". Since we are using a flexible model, it is not a problem to have some fields more than other datasets
- concerning the long description of data_source, It would be preferable to remove it in order to have smaller files. So @egregorimar can you please remove completely the field data_source description from the mapped data?

**Comment by egregorimar** [comment]
@bouffan @S-AI-F 
I have fixed the mapping (sorry for the mistake!) and removed the description

**Pull request merged**
